# Generated by Django 5.2.15 on 2026-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва товару')),
                ('url', models.URLField(unique=True, verbose_name='Посилання на товар')),
                ('currentPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Поточна ціна')),
                ('desiredPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Поточна ціна')),
                ('lastChecked', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
        ),
    ]
